# Generated by Django 2.2.7 on 2019-11-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('customer_code', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField(verbose_name='date ordered')),
                ('assign_date', models.DateTimeField(verbose_name='date assigned')),
                ('survey_locations', models.CharField(max_length=200)),
                ('depot_code', models.CharField(max_length=200)),
                ('depot_name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('release_number', models.CharField(max_length=200)),
                ('container_number', models.CharField(max_length=200)),
                ('survey_code', models.CharField(max_length=200)),
                ('remark', models.TextField()),
            ],
        ),
    ]
