# Generated by Django 2.2.7 on 2019-11-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='release_number',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
