# Generated by Django 2.2.7 on 2019-11-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assign_date',
            field=models.DateTimeField(verbose_name='date assigned'),
        ),
        migrations.AlterField(
            model_name='order',
            name='container_number',
            field=models.CharField(max_length=200),
        ),
    ]
