# Generated by Django 2.2.7 on 2019-11-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_auto_20191122_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='survey_location',
            new_name='survey_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='surveyor_code',
            new_name='survey_locations',
        ),
    ]
