# Generated by Django 2.2.7 on 2019-11-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_auto_20191126_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='release_number',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
