# Generated by Django 2.2.7 on 2019-11-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_auto_20191126_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='release_number',
        ),
    ]
