# Generated by Django 2.2.7 on 2019-11-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_remove_order_release_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='release_number',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
