# Generated by Django 2.2.7 on 2019-11-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0005_order_release_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='container_number',
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.Order')),
            ],
        ),
    ]
